eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8764
feign:
  hystrix:
    enabled: true
spring:
  application:
    name: greeting-service